---
- name: Developer Workstation Setup mit Scoop
  hosts: windows
  gather_facts: true

  tasks:
      - name: Wichtige Buckets hinzufügen
        community.windows.win_scoop_bucket:
          name: "{{ item }}"
          state: present
        loop:
          - extras
          - versions
          - main

      - name: Tool-Set installieren
        community.windows.win_scoop:
          name: "{{ item }}"
          state: present
        loop:
          - git
          - ripgrep
          - python
          - nodejs