# --- Untergruppen definieren ---

[domain_controllers]
dc01 ansible_host=dc01.corp.contoso.local

[app_servers]
member-0 ansible_host=member-0.corp.contoso.local
member-1 ansible_host=member-1.corp.contoso.local

[clients]
win11-client ansible_host=win11-client.corp.contoso.local

# --- Die Elterngruppe "windows" ---
# Hier fassen wir alle obigen Gruppen zusammen
[windows:children]
domain_controllers
app_servers
clients

# --- Variablen für ALLE Windows-Maschinen ---
[windows:vars]
ansible_connection=winrm
ansible_user=labadmin@corp.contoso.local
ansible_password="P@ssw0rd1234!"
ansible_winrm_transport=credssp
ansible_winrm_scheme=http
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

# --- Linux / Admin Server (Optional) ---
[admin_servers]
debian-01 ansible_connection=local